name: KBOT

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.KBOT_GAR_REGISTRY }}
        run: make image push